测速日志 2025-09-25 09:10:02
[2025-09-25 09:10:07] ✅ 测速成功: https://lotus.stingray.com/manifest/cmusic-cme004-montreal/samsungtvplus/dee3e3af-2706-3e77-a952-91b99f6d1819/5711200/manifest.m3u8
   速度: 2492.19KB/s | 数据量: 2.5KB | 总耗时: 0.29s
[2025-09-25 09:10:07] ✅ 测速成功: https://gitlab.com/p2v5/wangtv/-/raw/main/about1080p.mp4
   速度: 119357.78KB/s | 数据量: 8412.8KB | 总耗时: 0.36s
[2025-09-25 09:10:07] ✅ 测速成功: https://AMChls.wns.live/hls/stream.m3u8
   速度: 721.68KB/s | 数据量: 0.7KB | 总耗时: 0.36s
[2025-09-25 09:10:07] ✅ 测速成功: http://61.221.215.25:8800/hls/43/index.m3u8
   速度: 236.33KB/s | 数据量: 0.2KB | 总耗时: 0.39s
[2025-09-25 09:10:07] ✅ 测速成功: http://61.221.215.25:8800/hls/49/index.m3u8
   速度: 252.93KB/s | 数据量: 0.3KB | 总耗时: 0.39s
[2025-09-25 09:10:07] ✅ 测速成功: http://113.195.172.192:808/hls/113/index.m3u8
   速度: 229.49KB/s | 数据量: 0.2KB | 总耗时: 0.48s
[2025-09-25 09:10:07] ✅ 测速成功: http://113.195.172.192:808/hls/114/index.m3u8
   速度: 228.52KB/s | 数据量: 0.2KB | 总耗时: 0.50s
[2025-09-25 09:10:07] ✅ 测速成功: http://61.162.52.6:8088/newlive/live/hls/60/live.m3u8
   速度: 226.56KB/s | 数据量: 0.2KB | 总耗时: 0.51s
[2025-09-25 09:10:07] ✅ 测速成功: http://113.26.202.52:1299/tsfile/live/0002_1.m3u8
   速度: 408.20KB/s | 数据量: 0.4KB | 总耗时: 0.54s
[2025-09-25 09:10:07] ✅ 测速成功: http://120.198.95.220:9901/tsfile/live/1038_1.m3u8?key=txiptv
   速度: 658.20KB/s | 数据量: 0.7KB | 总耗时: 0.59s
[2025-09-25 09:10:07] ✅ 测速成功: http://123.146.162.24:8017/c2F0hmi/1000/live.m3u8
   速度: 438.48KB/s | 数据量: 0.4KB | 总耗时: 0.52s
[2025-09-25 09:10:07] ✅ 测速成功: http://123.146.162.24:8013/tslslive/PU2vzMI/hls/live_sd.m3u8?zzhongqd
   速度: 545.90KB/s | 数据量: 0.5KB | 总耗时: 0.55s
[2025-09-25 09:10:07] ✅ 测速成功: http://112.27.235.94:8000/hls/18/index.m3u8
   速度: 240.23KB/s | 数据量: 0.2KB | 总耗时: 0.42s
[2025-09-25 09:10:07] ✅ 测速成功: http://123.146.162.24:8013/tslslive/noEX9SG/hls/live_sd.m3u8?zzhongqd
   速度: 545.90KB/s | 数据量: 0.5KB | 总耗时: 0.51s
[2025-09-25 09:10:08] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/24/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.87s
[2025-09-25 09:10:08] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/33/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.87s
[2025-09-25 09:10:08] ✅ 测速成功: http://222.128.55.152:9080/live/dwq.m3u8
   速度: 0.35KB/s | 数据量: 0.1KB | 总耗时: 0.76s
[2025-09-25 09:10:08] ✅ 测速成功: http://112.27.235.94:8000/hls/25/index.m3u8
   速度: 240.23KB/s | 数据量: 0.2KB | 总耗时: 0.45s
[2025-09-25 09:10:08] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/45/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.86s
[2025-09-25 09:10:08] ✅ 测速成功: http://111.202.12.159:8080/kYGHWzA/1000/live.m3u8
   速度: 330.08KB/s | 数据量: 0.3KB | 总耗时: 0.51s
[2025-09-25 09:10:08] ✅ 测速成功: http://38.64.72.148:80/hls/modn/list/4009/chunklist0.m3u8
   速度: 397.46KB/s | 数据量: 0.4KB | 总耗时: 0.12s
[2025-09-25 09:10:08] ✅ 测速成功: http://111.202.12.159:8080/3zvkK28/1000/live.m3u8
   速度: 69.34KB/s | 数据量: 0.1KB | 总耗时: 0.51s
[2025-09-25 09:10:08] ✅ 测速成功: http://38.64.72.148:80/hls/modn/list/4009/playlist.m3u8
   速度: 227.54KB/s | 数据量: 0.2KB | 总耗时: 0.13s
[2025-09-25 09:10:08] ✅ 测速成功: http://38.64.72.148:80/hls/modn/list/4007/playlist.m3u8
   速度: 227.54KB/s | 数据量: 0.2KB | 总耗时: 0.12s
[2025-09-25 09:10:08] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/49/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.80s
[2025-09-25 09:10:08] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/38/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.80s
[2025-09-25 09:10:08] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/22/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.79s
[2025-09-25 09:10:08] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/47/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.80s
[2025-09-25 09:10:09] ✅ 测速成功: http://111.53.96.67:8081/live/1/index.m3u8
   速度: 208.98KB/s | 数据量: 0.2KB | 总耗时: 0.48s
[2025-09-25 09:10:09] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/36/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.81s
[2025-09-25 09:10:09] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/46/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.78s
[2025-09-25 09:10:09] ✅ 测速成功: http://111.53.96.67:8081/live/1/index.m3u8?%E5%85%B3%E6%B3%A8%E5%BE%AE%E4%BF%A1%E5%85%AC%E4%BC%97%E5%8F%B7[%E6%99%B4%E5%9B%AD]
   速度: 208.98KB/s | 数据量: 0.2KB | 总耗时: 0.47s
[2025-09-25 09:10:09] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/48/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.78s
[2025-09-25 09:10:09] ✅ 测速成功: http://36.32.174.67:60080/newlive/live/hls/34/live.m3u8
   速度: 232.42KB/s | 数据量: 0.2KB | 总耗时: 0.78s
[2025-09-25 09:10:10] ✅ 测速成功: https://cloud.video.taobao.com//play/u/57349687/p/1/e/6/t/1/240192067467.mp4
   速度: 42210.23KB/s | 数据量: 31831.9KB | 总耗时: 3.46s
[2025-09-25 09:10:11] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.241:8000
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.241:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cf50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:12] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.159:8000
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.159:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d250>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:12] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.158:8000
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.158:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d350>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:12] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.242:8000
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.242:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d750>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:12] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.116:8000
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.116:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d650>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:12] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.117:8000
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.117:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d550>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:12] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.115:8000
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.115:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d050>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:12] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.189:8000
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.189:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cd50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:12] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.243:8000
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.243:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498c950>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:13] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.235:8000
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.235:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d450>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:14] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.129:8008
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.129:8008 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498da50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:15] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.60:8084
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.60:8084 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498de50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:15] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.172:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.172:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e250>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:15] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.105:8092
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.105:8092 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e650>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:15] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.173:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.173:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d650>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:15] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.130:8004
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.130:8004 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e450>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:15] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.174:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.174:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498df50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:15] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.61:8104
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.61:8104 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cf50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:15] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.175:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.175:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498eb50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:16] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.62:8112
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.62:8112 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498ef50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:17] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.63:8116
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.63:8116 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f250>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:18] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.152:8120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.152:8120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f550>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:18] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.64:8124
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.64:8124 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f850>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:18] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.124:8128
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.124:8128 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fb50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:18] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.65:8132
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.65:8132 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fe50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:18] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.153:8136
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.153:8136 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4250>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:18] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.184:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.184:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4550>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:18] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.151:8144
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.151:8144 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4850>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:18] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.132:8012
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.132:8012 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4b50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:19] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.136:8032
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.136:8032 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498ef50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:20] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.137:8036
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.137:8036 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498df50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:21] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.135:8028
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.135:8028 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fd50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:21] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.134:8020
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.134:8020 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fa50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:21] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.142:8048
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.142:8048 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f750>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:21] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.211:8064
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.211:8064 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f450>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:21] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.141:1234
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.141:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f150>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:21] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.122:8160
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.122:8160 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498ed50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:21] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.209:8052
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.209:8052 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d150>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:21] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.148:8072
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.148:8072 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498dc50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:22] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.210:8056
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.210:8056 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d350>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:23] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.138:8044
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.138:8044 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e750>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:24] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.240:8172
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.240:8172 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4c50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:24] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.149:8076
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.149:8076 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4750>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:24] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.156:8148
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.156:8148 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4350>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:24] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.123:8164
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.123:8164 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4f50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:24] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.45:8304
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.45:8304 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f150>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:24] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.133:8016
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.133:8016 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fa50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:24] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.26:8108
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.26:8108 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498df50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:24] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.29:8288
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.29:8288 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498ef50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:25] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.46:8124
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.46:8124 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cd50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:26] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.42:8172
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.42:8172 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498ec50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:27] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.39:8300
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.39:8300 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498da50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:27] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.48:8160
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.48:8160 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498de50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:27] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.27:8128
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.27:8128 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e250>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:27] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.49:8188
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.49:8188 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e650>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:27] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.47:8164
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.47:8164 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d650>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:27] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.41:8140
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.41:8140 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cf50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:27] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.44:8184
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.44:8184 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e5150>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:27] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.43:8176
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.43:8176 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4150>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:28] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.155:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.155:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4950>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:30] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.143:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.143:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4b50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:30] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.144:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.144:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498da50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:30] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.236:2000
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.236:2000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498ef50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:30] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.249:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.249:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fa50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:30] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.250:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.250:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f150>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:30] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.95:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.95:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f850>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:30] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.100:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.100:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f650>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:30] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.238:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.238:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f050>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:30] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.102:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.102:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498c950>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:31] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.213:4220
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.213:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d250>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:33] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.214:4220
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.214:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e350>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:33] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.215:4220
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.215:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e850>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:33] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.216:4220
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.216:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f750>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:33] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.217:4220
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.217:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4850>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:33] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.218:4220
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.218:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4650>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:33] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.219:4220
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.219:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e5050>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:33] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.220:4220
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.220:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4350>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:33] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.57:8152
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.57:8152 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4250>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:33] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.54:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.54:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f050>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:34] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.56:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.56:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f150>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:36] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.188:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.188:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498ef50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:36] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.163:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.163:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498da50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:36] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.221:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.221:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498dc50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:36] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.96:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.96:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d950>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:36] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.154:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.154:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f350>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:36] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.187:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.187:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fb50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:36] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.58:8156
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.58:8156 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fc50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:36] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.165:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.165:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e450>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:36] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.164:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.164:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498eb50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:37] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.94:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.94:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cd50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:39] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.92:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.92:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4750>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:39] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.91:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.91:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4e50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:39] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.93:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.93:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4d50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:39] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.74:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.74:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4950>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:39] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.195:9024
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.195:9024 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f350>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:39] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.194:9020
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.194:9020 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498da50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:39] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.68:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.68:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f150>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:39] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.67:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.67:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f050>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:39] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.90:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.90:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e650>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:40] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.196:9012
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.196:9012 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f950>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:42] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.69:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.69:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d450>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:42] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.199:9000
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.199:9000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d050>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:42] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.80:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.80:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d150>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:42] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.51:9252
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.51:9252 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498ed50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:42] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.147:9268
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.147:9268 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fa50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:42] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.71:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.71:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f650>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:42] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.75:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.75:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4b50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:42] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.76:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.76:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4450>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:42] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.85:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.85:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4c50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:43] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.77:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.77:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e5050>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:45] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.83:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.83:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d450>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:45] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.81:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.81:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f150>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:45] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.52:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.52:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d250>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:45] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.78:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.78:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e350>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:45] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.193:8012
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.193:8012 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d550>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:45] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.79:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.79:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d350>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:45] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.87:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.87:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cf50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:45] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.86:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.86:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f550>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:45] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.73:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.73:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e250>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:47] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.72:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.72:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498de50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:48] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.89:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.89:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498ef50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:48] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.70:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.70:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4650>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:48] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.82:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.82:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d950>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:48] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.84:4120
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.84:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4f50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:48] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.125:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.125:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4550>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:48] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.126:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.126:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4950>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:48] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.127:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.127:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cf50>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:48] ❌ 测速失败: http://114.241.215.201:4022/rtp/239.3.1.128:8001
   错误: HTTPConnectionPool(host='114.241.215.201', port=4022): Max retries exceeded with url: /rtp/239.3.1.128:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e350>, 'Connection to 114.241.215.201 timed out. (connect timeout=3.05)')) | 域名: 114.241.215.201
[2025-09-25 09:10:48] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.241:8000
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.241:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f150>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:50] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.159:8000
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.159:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d450>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:51] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.158:8000
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.158:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498df50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:51] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.242:8000
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.242:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498eb50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:51] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.116:8000
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.116:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fe50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:51] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.117:8000
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.117:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e650>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:51] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.115:8000
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.115:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e850>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:51] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.189:8000
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.189:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f450>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:51] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.243:8000
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.243:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f850>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:52] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.235:8000
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.235:8000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f050>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:52] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.129:8008
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.129:8008 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4d50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:53] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.60:8084
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.60:8084 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4a50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:54] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.172:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.172:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4350>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:54] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.173:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.173:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4750>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:54] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.105:8092
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.105:8092 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4c50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:54] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.130:8004
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.130:8004 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fe50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:54] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.174:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.174:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d450>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:54] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.61:8104
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.61:8104 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e350>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:54] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.175:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.175:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cf50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:55] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.62:8112
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.62:8112 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498ed50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:55] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.63:8116
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.63:8116 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f750>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:56] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.152:8120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.152:8120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d950>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:57] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.64:8124
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.64:8124 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f250>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:57] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.124:8128
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.124:8128 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fc50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:57] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.65:8132
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.65:8132 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fb50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:57] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.153:8136
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.153:8136 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498c950>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:57] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.184:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.184:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d550>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:57] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.151:8144
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.151:8144 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4450>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:57] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.132:8012
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.132:8012 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4250>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:58] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.136:8032
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.136:8032 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e5150>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:58] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.137:8036
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.137:8036 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4550>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:10:59] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.135:8028
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.135:8028 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d950>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:00] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.134:8020
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.134:8020 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cf50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:00] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.142:8048
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.142:8048 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d450>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:00] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.211:8064
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.211:8064 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fe50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:00] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.141:1234
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.141:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498de50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:00] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.122:8160
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.122:8160 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e450>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:00] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.209:8052
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.209:8052 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f650>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:01] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.148:8072
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.148:8072 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fd50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:01] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.210:8056
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.210:8056 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d150>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:01] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.138:8044
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.138:8044 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d050>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:02] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.240:8172
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.240:8172 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f150>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:03] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.149:8076
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.149:8076 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498eb50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:03] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.156:8148
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.156:8148 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4950>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:03] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.123:8164
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.123:8164 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4050>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:03] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.45:8304
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.45:8304 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4b50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:04] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.133:8016
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.133:8016 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4350>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:04] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.26:8108
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.26:8108 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f650>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:04] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.29:8288
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.29:8288 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fe50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:04] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.46:8124
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.46:8124 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498df50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:04] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.42:8172
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.42:8172 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f450>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:05] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.39:8300
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.39:8300 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f350>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:06] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.48:8160
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.48:8160 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e750>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:07] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.27:8128
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.27:8128 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d550>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:07] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.49:8188
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.49:8188 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498ec50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:07] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.47:8164
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.47:8164 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e250>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:07] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.41:8140
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.41:8140 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f550>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:07] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.44:8184
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.44:8184 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e350>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:07] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.43:8176
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.43:8176 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f750>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:07] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.155:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.155:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4750>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:07] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.143:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.143:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4850>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:08] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.144:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.144:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4f50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:09] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.236:2000
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.236:2000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e5150>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:10] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.249:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.249:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d550>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:10] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.250:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.250:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f450>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:10] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.95:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.95:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498ed50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:10] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.100:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.100:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d350>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:10] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.238:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.238:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fb50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:10] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.102:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.102:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d950>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:10] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.213:4220
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.213:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cd50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:10] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.214:4220
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.214:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f050>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:11] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.215:4220
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.215:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498da50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:12] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.216:4220
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.216:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e850>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:13] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.217:4220
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.217:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d450>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:13] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.218:4220
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.218:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e450>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:13] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.219:4220
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.219:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4550>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:13] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.220:4220
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.220:4220 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4150>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:13] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.57:8152
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.57:8152 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4a50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:13] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.54:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.54:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4b50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:13] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.56:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.56:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e5450>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:13] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.188:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.188:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fb50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:14] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.163:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.163:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f450>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:15] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.221:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.221:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d550>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:16] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.96:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.96:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f950>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:16] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.154:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.154:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f150>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:16] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.187:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.187:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d650>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:16] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.58:8156
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.58:8156 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498c950>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:16] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.165:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.165:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d250>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:16] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.164:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.164:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f650>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:16] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.94:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.94:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fe50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:16] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.92:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.92:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f350>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:17] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.91:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.91:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4050>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:18] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.93:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.93:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4c50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:19] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.74:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.74:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4650>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:19] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.195:9024
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.195:9024 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e5150>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:19] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.194:9020
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.194:9020 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4750>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:19] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.68:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.68:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d650>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:19] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.67:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.67:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d550>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:19] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.90:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.90:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fb50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:19] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.196:9012
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.196:9012 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e250>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:19] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.69:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.69:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fc50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:20] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.199:9000
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.199:9000 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f750>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:21] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.80:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.80:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fa50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:22] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.51:9252
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.51:9252 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d050>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:22] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.147:9268
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.147:9268 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cf50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:22] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.71:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.71:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498de50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:22] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.75:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.75:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d350>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:22] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.76:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.76:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cd50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:22] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.85:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.85:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4450>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:22] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.77:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.77:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e5050>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:22] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.83:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.83:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4950>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:23] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.81:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.81:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4a50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:25] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.52:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.52:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fa50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:25] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.78:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.78:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e250>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:25] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.193:8012
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.193:8012 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d950>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:25] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.79:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.79:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498ed50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:25] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.87:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.87:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e850>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:25] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.86:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.86:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e450>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:25] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.73:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.73:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498dc50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:25] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.72:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.72:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f550>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:25] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.89:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.89:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498df50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:26] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.82:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.82:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f650>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:28] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.70:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.70:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d250>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:28] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.84:4120
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.84:4120 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4550>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:28] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.125:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.125:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e5450>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:28] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.126:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.126:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4e50>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:28] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.127:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.127:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4850>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:28] ❌ 测速失败: http://114.254.33.175:8888/rtp/239.3.1.128:8001
   错误: HTTPConnectionPool(host='114.254.33.175', port=8888): Max retries exceeded with url: /rtp/239.3.1.128:8001 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4650>, 'Connection to 114.254.33.175 timed out. (connect timeout=3.05)')) | 域名: 114.254.33.175
[2025-09-25 09:11:31] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.236:5140
   速度: 1010.80KB/s | 数据量: 5120.0KB | 总耗时: 5.62s
[2025-09-25 09:11:31] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.0.9:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.12s
[2025-09-25 09:11:31] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.46:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.13s
[2025-09-25 09:11:31] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.55:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.18s
[2025-09-25 09:11:31] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.146:5140
   速度: 1085.44KB/s | 数据量: 6144.0KB | 总耗时: 6.20s
[2025-09-25 09:11:32] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.209:5140
   速度: 941.70KB/s | 数据量: 6144.0KB | 总耗时: 7.08s
[2025-09-25 09:11:32] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.237:5140
   速度: 1090.89KB/s | 数据量: 6144.0KB | 总耗时: 6.18s
[2025-09-25 09:11:34] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.136:5140
   速度: 1096.29KB/s | 数据量: 6144.0KB | 总耗时: 6.16s
[2025-09-25 09:11:34] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.134:5140
   速度: 1098.49KB/s | 数据量: 6144.0KB | 总耗时: 6.15s
[2025-09-25 09:11:34] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.132:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.98s
[2025-09-25 09:11:34] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.210:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.92s
[2025-09-25 09:11:34] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.0.17:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.98s
[2025-09-25 09:11:34] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.0.13:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.98s
[2025-09-25 09:11:34] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.196:5140
   速度: 1092.35KB/s | 数据量: 6144.0KB | 总耗时: 6.19s
[2025-09-25 09:11:35] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.135:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.65s
[2025-09-25 09:11:37] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.69:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-25 09:11:37] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.56:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-25 09:11:37] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.0.2:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-25 09:11:37] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.131:5140
   速度: 1011.18KB/s | 数据量: 6144.0KB | 总耗时: 6.68s
[2025-09-25 09:11:38] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.211:5140
   速度: 1104.32KB/s | 数据量: 6144.0KB | 总耗时: 6.11s
[2025-09-25 09:11:40] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.145:5140
   速度: 1101.29KB/s | 数据量: 6144.0KB | 总耗时: 6.12s
[2025-09-25 09:11:40] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.8:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-25 09:11:40] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.196:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-25 09:11:40] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.4:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-25 09:11:40] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.10:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.65s
[2025-09-25 09:11:40] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.70:5140
   速度: 789.50KB/s | 数据量: 4096.0KB | 总耗时: 6.37s
[2025-09-25 09:11:41] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.198:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.79s
[2025-09-25 09:11:41] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.68:5140
   速度: 1102.77KB/s | 数据量: 6144.0KB | 总耗时: 7.18s
[2025-09-25 09:11:41] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.71:5140
   速度: 363.15KB/s | 数据量: 2048.0KB | 总耗时: 6.24s
[2025-09-25 09:11:42] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.208:5140
   速度: 301.43KB/s | 数据量: 2048.0KB | 总耗时: 7.56s
[2025-09-25 09:11:43] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.42:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-25 09:11:43] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.200:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-25 09:11:43] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.52:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-25 09:11:44] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.10:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.82s
[2025-09-25 09:11:44] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.139:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.76s
[2025-09-25 09:11:46] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.23:5140
   速度: 1119.02KB/s | 数据量: 6144.0KB | 总耗时: 6.07s
[2025-09-25 09:11:46] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.229:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-25 09:11:46] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.178:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-25 09:11:46] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.177:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-25 09:11:47] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.107:5140
   速度: 1612.82KB/s | 数据量: 8192.0KB | 总耗时: 5.61s
[2025-09-25 09:11:47] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.228:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-25 09:11:47] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.239:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-25 09:11:48] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.1:5140
   速度: 1228.17KB/s | 数据量: 6144.0KB | 总耗时: 7.57s
[2025-09-25 09:11:49] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.4:5140
   速度: 545.10KB/s | 数据量: 3072.0KB | 总耗时: 8.48s
[2025-09-25 09:11:49] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.29:5140
   速度: 497.69KB/s | 数据量: 3072.0KB | 总耗时: 6.95s
[2025-09-25 09:11:49] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.230:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.02s
[2025-09-25 09:11:50] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.122:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-25 09:11:51] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.0.3:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.51s
[2025-09-25 09:11:51] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.81:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.51s
[2025-09-25 09:11:51] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.44:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.06s
[2025-09-25 09:11:51] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.0.5:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 4.00s
[2025-09-25 09:11:52] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.238:5140
   速度: 1102.11KB/s | 数据量: 6144.0KB | 总耗时: 6.17s
[2025-09-25 09:11:53] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.121:5140
   速度: 781.26KB/s | 数据量: 4096.0KB | 总耗时: 5.81s
[2025-09-25 09:11:53] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.120:5140
   速度: 1031.90KB/s | 数据量: 6144.0KB | 总耗时: 6.92s
[2025-09-25 09:11:53] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.124:5140
   速度: 1101.77KB/s | 数据量: 6144.0KB | 总耗时: 7.17s
[2025-09-25 09:11:54] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.80:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-25 09:11:54] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.0.6:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-25 09:11:54] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.0.4:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-25 09:11:55] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.123:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.83s
[2025-09-25 09:11:55] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.231:5140
   速度: 1090.52KB/s | 数据量: 6144.0KB | 总耗时: 6.20s
[2025-09-25 09:11:56] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.230:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.97s
[2025-09-25 09:11:56] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.229:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.08s
[2025-09-25 09:11:56] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.83:5140
   速度: 1099.78KB/s | 数据量: 6144.0KB | 总耗时: 6.15s
[2025-09-25 09:11:57] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.231:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-25 09:11:57] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.232:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-25 09:11:57] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.84:5140
   速度: 531.64KB/s | 数据量: 3072.0KB | 总耗时: 6.35s
[2025-09-25 09:11:58] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.234:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.78s
[2025-09-25 09:11:58] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.0.4:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-25 09:11:59] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.232:5140
   速度: 571.49KB/s | 数据量: 3072.0KB | 总耗时: 6.47s
[2025-09-25 09:11:59] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.116:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.84s
[2025-09-25 09:12:00] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.117:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-25 09:12:00] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.251:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.65s
[2025-09-25 09:12:00] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.82:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-25 09:12:01] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.213:5140
   速度: 354.98KB/s | 数据量: 2048.0KB | 总耗时: 6.42s
[2025-09-25 09:12:01] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.0.38:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-25 09:12:02] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.14:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.99s
[2025-09-25 09:12:02] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.0.8:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.09s
[2025-09-25 09:12:03] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.238:5140
   速度: 353.69KB/s | 数据量: 2048.0KB | 总耗时: 6.44s
[2025-09-25 09:12:03] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.0.3:5140
   速度: 1117.56KB/s | 数据量: 6144.0KB | 总耗时: 6.58s
[2025-09-25 09:12:03] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.50:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-25 09:12:03] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.52:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.01s
[2025-09-25 09:12:03] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.194:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.59s
[2025-09-25 09:12:04] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.45:5140
   速度: 1005.18KB/s | 数据量: 5120.0KB | 总耗时: 5.64s
[2025-09-25 09:12:05] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.74:5140
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 3.00s
[2025-09-25 09:12:06] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.126:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.126:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f150>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:06] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.154:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.154:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cf50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:06] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.25:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.25:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498da50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:06] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.125:5140
   速度: 910.06KB/s | 数据量: 5120.0KB | 总耗时: 6.19s
[2025-09-25 09:12:07] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.164:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.164:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d550>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:07] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.185:5140
   速度: 192.21KB/s | 数据量: 1024.0KB | 总耗时: 6.11s
[2025-09-25 09:12:08] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.150:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.150:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498eb50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:08] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.75:5140
   速度: 816.87KB/s | 数据量: 4096.0KB | 总耗时: 5.71s
[2025-09-25 09:12:09] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.1.48:5140
   速度: 353.48KB/s | 数据量: 2048.0KB | 总耗时: 6.45s
[2025-09-25 09:12:09] ✅ 测速成功: http://223.167.230.34:4022/rtp/239.45.3.207:5140
   速度: 1097.22KB/s | 数据量: 6144.0KB | 总耗时: 6.15s
[2025-09-25 09:12:09] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.241:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.241:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d150>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:09] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.151:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.151:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f750>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:09] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.168:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.168:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e5150>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:09] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.156:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.156:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498dc50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:10] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.165:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.165:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4250>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:10] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.27:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.27:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f450>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:11] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.135:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.135:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4b50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:11] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.170:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.170:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498ed50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:12] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.201:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.201:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fb50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:12] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.171:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.171:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498ec50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:12] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.93:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.93:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4950>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:12] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.172:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.172:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e5750>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:12] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.136:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.136:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f750>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:12] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.173:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.173:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d550>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:13] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.137:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.137:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fc50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:13] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.138:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.138:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f050>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:14] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.178:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.178:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498de50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:14] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.139:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.139:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f850>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:15] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.15:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.15:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e350>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:15] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.140:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.140:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d250>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:15] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.179:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.179:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f650>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:15] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.182:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.182:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498df50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:15] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.230:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.230:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f550>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:15] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.29:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.29:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e5150>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:16] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.38:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.38:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4450>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:16] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.45:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.45:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4150>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:17] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.52:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.52:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4f50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:17] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.47:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.47:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4050>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:18] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.60:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.60:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e350>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:18] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.56:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.56:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fc50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:18] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.63:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.63:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e850>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:18] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.58:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.58:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e250>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:18] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.51:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.51:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e750>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:18] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.206:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.206:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498ec50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:19] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.117:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.117:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fb50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:19] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.125:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.125:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498ed50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:20] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.122:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.122:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d650>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:20] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.123:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.123:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f150>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:21] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.116:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.116:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498da50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:21] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.141:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.141:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d150>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:21] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.115:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.115:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4c50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:21] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.181:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.181:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4350>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:21] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.131:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.131:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e5850>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:22] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.130:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.130:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4950>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:22] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.124:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.124:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fb50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:22] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.185:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.185:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e250>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:23] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.186:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.186:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498eb50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:23] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.74:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.74:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cf50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:24] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.110:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.110:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f350>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:24] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.26:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.26:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cd50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:24] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.82:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.82:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f550>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:24] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.95:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.95:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fe50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:24] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.49:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.49:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498df50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:25] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.80:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.80:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f650>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:25] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.101:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.101:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d250>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:26] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.40:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.40:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498c950>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:26] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.35:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.35:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4b50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:27] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.111:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.111:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e5050>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:27] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.34:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.34:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4750>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:27] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.180:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.180:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4050>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:28] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.76:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.76:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4450>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:28] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.86:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.86:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f550>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:28] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.18:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.18:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cf50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:28] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.50:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.50:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e250>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:28] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.114:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.114:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fb50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:29] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.160:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.160:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f750>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:30] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.212:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.212:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fa50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:30] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.238:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.238:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f250>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:30] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.239:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.239:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d350>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:30] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.169:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.169:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f450>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:31] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.67:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.67:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e350>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:31] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.161:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.161:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fc50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:31] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.163:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.163:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e750>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:31] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.90:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.90:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4f50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:31] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.162:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.162:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4d50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:32] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.98:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.98:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e5750>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:33] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.107:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.107:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e5850>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:33] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.108:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.108:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f250>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:33] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.127:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.127:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fb50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:33] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.128:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.128:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cf50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:34] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.133:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.133:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f550>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:34] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.134:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.134:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f150>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:34] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.149:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.149:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fd50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:34] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.53:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.53:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498de50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:34] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.59:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.59:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d950>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:35] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.188:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.188:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d550>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:36] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.198:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.198:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f850>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:36] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.28:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.28:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498eb50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:36] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.6:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.6:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498cd50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:36] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.43:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.43:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4950>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:37] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.8:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.8:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4a50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:37] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.103:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.103:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4150>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:37] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.159:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.159:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4750>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:37] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.157:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.157:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498de50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:37] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.57:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.57:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f550>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:38] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.104:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.104:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498f350>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:39] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.105:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.105:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e650>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:39] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.109:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.109:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e450>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:39] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.102:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.102:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d450>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:39] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.213:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.213:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e750>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:40] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.119:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.119:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498ed50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:40] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.148:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.148:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fc50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:40] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.118:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.118:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498d650>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:40] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.187:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.187:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e250>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:40] ✅ 测速成功: http://203.205.191.53/qctv.fengshows.cn/live/0701pin72.m3u8
   速度: 294.92KB/s | 数据量: 0.3KB | 总耗时: 0.15s
[2025-09-25 09:12:40] ✅ 测速成功: http://203.205.191.53/qctv.fengshows.cn/live/0701pcc72.m3u8
   速度: 294.92KB/s | 数据量: 0.3KB | 总耗时: 0.16s
[2025-09-25 09:12:40] ✅ 测速成功: http://203.205.191.53/qctv.fengshows.cn/live/0701phk72.m3u8
   速度: 294.92KB/s | 数据量: 0.3KB | 总耗时: 0.13s
[2025-09-25 09:12:40] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv066
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.19s
[2025-09-25 09:12:40] ✅ 测速成功: https://kakaxi-1.github.io/IPTV/LOGO/Disclaimer.mp4
   速度: 136878.11KB/s | 数据量: 19744.2KB | 总耗时: 0.37s
[2025-09-25 09:12:40] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv040
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.03s
[2025-09-25 09:12:40] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv066
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.34s
[2025-09-25 09:12:40] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.203:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.203:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498fa50>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:40] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv041
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.04s
[2025-09-25 09:12:40] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv040
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.34s
[2025-09-25 09:12:41] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv041
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:41] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv002
   速度: 579.10KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:41] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.197:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.197:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4050>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:41] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv155
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.04s
[2025-09-25 09:12:41] ✅ 测速成功: http://61.216.11.93:49981/stream/channelid/1736257299?profile=webtv-h264-aac-mpegts
   速度: 421.88KB/s | 数据量: 0.4KB | 总耗时: 0.38s
[2025-09-25 09:12:41] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv073
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.03s
[2025-09-25 09:12:41] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv002
   速度: 585.94KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:41] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv155
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:41] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv067
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:41] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv068
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.04s
[2025-09-25 09:12:41] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv073
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:42] ✅ 测速成功: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=4gtv-4gtv040&sd=1080&proxy=false
   速度: 2332.03KB/s | 数据量: 2.3KB | 总耗时: 1.43s
[2025-09-25 09:12:42] ✅ 测速成功: http://61.216.11.93:49981/stream/channelid/1607444205?profile=webtv-h264-aac-mpegts
   速度: 151.37KB/s | 数据量: 0.2KB | 总耗时: 0.38s
[2025-09-25 09:12:42] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv068
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:42] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv067
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.44s
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv072
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.07s
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-ftv13
   速度: 564.45KB/s | 数据量: 0.6KB | 总耗时: 0.04s
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv001
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv003
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.06s
[2025-09-25 09:12:42] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.48:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.48:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4650>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:42] ✅ 测速成功: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=4gtv-4gtv041&sd=1080&proxy=false
   速度: 2332.03KB/s | 数据量: 2.3KB | 总耗时: 1.43s
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-ftv07
   速度: 564.45KB/s | 数据量: 0.6KB | 总耗时: 0.04s
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv004
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.03s
[2025-09-25 09:12:42] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.155:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.155:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e4350>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-ftv09
   速度: 564.45KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:42] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv072
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv064
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:42] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=litv-ftv13
   速度: 571.29KB/s | 数据量: 0.6KB | 总耗时: 0.34s
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv080
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.03s
[2025-09-25 09:12:42] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv001
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.34s
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv074
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.03s
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv109
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:42] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv003
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.34s
[2025-09-25 09:12:42] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=litv-ftv07
   速度: 571.29KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv009
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:42] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.214:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.214:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa46e5750>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:42] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv004
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv152
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:42] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=litv-ftv09
   速度: 571.29KB/s | 数据量: 0.6KB | 总耗时: 0.34s
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv075
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:42] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv064
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv010
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:42] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv080
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv051
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:42] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv109
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-longturn14
   速度: 593.75KB/s | 数据量: 0.6KB | 总耗时: 0.03s
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv052
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.09s
[2025-09-25 09:12:42] ❌ 测速失败: http://116.2.167.104:4010/rtp/232.0.0.215:1234
   错误: HTTPConnectionPool(host='116.2.167.104', port=4010): Max retries exceeded with url: /rtp/232.0.0.215:1234 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9aa498e750>, 'Connection to 116.2.167.104 timed out. (connect timeout=3.05)')) | 域名: 116.2.167.104
[2025-09-25 09:12:42] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv009
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:42] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv152
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:42] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv156
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.03s
[2025-09-25 09:12:43] ✅ 测速成功: http://61.216.11.93:49981/stream/channelid/1254660478?profile=webtv-h264-aac-mpegts
   速度: 421.88KB/s | 数据量: 0.4KB | 总耗时: 0.38s
[2025-09-25 09:12:43] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv075
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.35s
[2025-09-25 09:12:43] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv153
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:43] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv010
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:43] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=litv-longturn14
   速度: 600.59KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:43] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv156
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.49s
[2025-09-25 09:12:43] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv048
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.06s
[2025-09-25 09:12:43] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv056
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:43] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv104
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.06s
[2025-09-25 09:12:43] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv158
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.83s
[2025-09-25 09:12:43] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv153
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.92s
[2025-09-25 09:12:44] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv049
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.03s
[2025-09-25 09:12:44] ✅ 测速成功: http://udnhls.skilldns.com/dsmz.m3u8
   速度: 160.16KB/s | 数据量: 0.2KB | 总耗时: 1.06s
[2025-09-25 09:12:44] ✅ 测速成功: http://udnhls.skilldns.com:80/dsmz.m3u8
   速度: 160.16KB/s | 数据量: 0.2KB | 总耗时: 0.94s
[2025-09-25 09:12:44] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv046
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:44] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv104
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:44] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv063
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.03s
[2025-09-25 09:12:44] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv065
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:44] ✅ 测速成功: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=4gtv-4gtv158&sd=1080&proxy=false
   速度: 2383.79KB/s | 数据量: 2.4KB | 总耗时: 1.27s
[2025-09-25 09:12:44] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv049
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:44] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv054
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.11s
[2025-09-25 09:12:44] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv062
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.07s
[2025-09-25 09:12:44] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv046
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:44] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv063
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:44] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv061
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:44] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv055
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:44] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv065
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:44] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv047
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.04s
[2025-09-25 09:12:44] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv058
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:44] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv054
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:44] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv044
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.03s
[2025-09-25 09:12:44] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv061
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.34s
[2025-09-25 09:12:44] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv062
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.43s
[2025-09-25 09:12:44] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv047
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:44] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv045
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.06s
[2025-09-25 09:12:44] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv058
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:44] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv057
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.04s
[2025-09-25 09:12:44] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-longturn01
   速度: 593.75KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:45] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv044
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:45] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv045
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:45] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv057
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:45] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-longturn18
   速度: 593.75KB/s | 数据量: 0.6KB | 总耗时: 0.04s
[2025-09-25 09:12:45] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=litv-longturn01
   速度: 600.59KB/s | 数据量: 0.6KB | 总耗时: 0.38s
[2025-09-25 09:12:45] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-longturn11
   速度: 593.75KB/s | 数据量: 0.6KB | 总耗时: 0.04s
[2025-09-25 09:12:45] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=litv-longturn18
   速度: 600.59KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:45] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-longturn12
   速度: 593.75KB/s | 数据量: 0.6KB | 总耗时: 0.04s
[2025-09-25 09:12:45] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=litv-longturn11
   速度: 600.59KB/s | 数据量: 0.6KB | 总耗时: 0.44s
[2025-09-25 09:12:46] ✅ 测速成功: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=4gtv-4gtv009&sd=1080&proxy=false
   速度: 2332.03KB/s | 数据量: 2.3KB | 总耗时: 3.49s
[2025-09-25 09:12:46] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-longturn21
   速度: 593.75KB/s | 数据量: 0.6KB | 总耗时: 0.03s
[2025-09-25 09:12:46] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=litv-longturn12
   速度: 600.59KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:46] ✅ 测速成功: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=litv-longturn01&sd=1080&proxy=false
   速度: 2403.32KB/s | 数据量: 2.4KB | 总耗时: 1.43s
[2025-09-25 09:12:46] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-longturn03
   速度: 593.75KB/s | 数据量: 0.6KB | 总耗时: 0.03s
[2025-09-25 09:12:46] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=litv-longturn21
   速度: 600.59KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:46] ❌ 测速失败: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=4gtv-4gtv066&sd=1080&proxy=false
   错误: HTTPSConnectionPool(host='pxuchylhjchl.us-east-1.clawcloudrun.com', port=443): Read timed out. (read timeout=3.05) | 域名: pxuchylhjchl.us-east-1.clawcloudrun.com
[2025-09-25 09:12:46] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-longturn02
   速度: 593.75KB/s | 数据量: 0.6KB | 总耗时: 0.05s
[2025-09-25 09:12:46] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=litv-longturn03
   速度: 600.59KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:46] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-longturn22
   速度: 593.75KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:47] ✅ 测速成功: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=litv-longturn12&sd=1080&proxy=false
   速度: 2396.48KB/s | 数据量: 2.4KB | 总耗时: 1.43s
[2025-09-25 09:12:47] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=litv-longturn22
   速度: 600.59KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:47] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv070
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:48] ✅ 测速成功: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=litv-longturn02&sd=1080&proxy=false
   速度: 2403.32KB/s | 数据量: 2.4KB | 总耗时: 1.43s
[2025-09-25 09:12:48] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv011
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:48] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv011
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:48] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv017
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:48] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-ftv10
   速度: 564.45KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:48] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-ftv03
   速度: 564.45KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:48] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv013
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.01s
[2025-09-25 09:12:48] ✅ 测速成功: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=4gtv-4gtv104&sd=1080&proxy=false
   速度: 2376.95KB/s | 数据量: 2.4KB | 总耗时: 4.98s
[2025-09-25 09:12:48] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv076
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.01s
[2025-09-25 09:12:48] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv076
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:48] ❌ 测速失败: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=litv-longturn14&sd=1080&proxy=false
   错误: HTTPSConnectionPool(host='pxuchylhjchl.us-east-1.clawcloudrun.com', port=443): Read timed out. (read timeout=5) | 域名: pxuchylhjchl.us-east-1.clawcloudrun.com
[2025-09-25 09:12:48] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv018
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:48] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-longturn19
   速度: 593.75KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:49] ✅ 测速成功: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=litv-longturn18&sd=1080&proxy=false
   速度: 2403.32KB/s | 数据量: 2.4KB | 总耗时: 4.21s
[2025-09-25 09:12:49] ✅ 测速成功: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=litv-longturn11&sd=1080&proxy=false
   速度: 2396.48KB/s | 数据量: 2.4KB | 总耗时: 4.03s
[2025-09-25 09:12:49] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv018
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:49] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv042
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:49] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv034
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:49] ✅ 测速成功: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=4gtv-4gtv156&sd=1080&proxy=false
   速度: 2383.79KB/s | 数据量: 2.4KB | 总耗时: 6.41s
[2025-09-25 09:12:49] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv039
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:49] ✅ 测速成功: https://iptv.vip-tptv.xyz/litv.php?id=4gtv-4gtv034
   速度: 6265.62KB/s | 数据量: 6.3KB | 总耗时: 0.19s
[2025-09-25 09:12:49] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv006
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:49] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=litv-longturn19
   速度: 600.59KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:49] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv014
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:49] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv034
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:49] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv053
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:49] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=4gtv-4gtv101
   速度: 576.17KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:49] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv039
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.44s
[2025-09-25 09:12:49] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-longturn04
   速度: 593.75KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:49] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-longturn05
   速度: 593.75KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:49] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-longturn06
   速度: 593.75KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:49] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv006
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.34s
[2025-09-25 09:12:49] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-longturn08
   速度: 593.75KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:49] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-longturn07
   速度: 593.75KB/s | 数据量: 0.6KB | 总耗时: 0.04s
[2025-09-25 09:12:49] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-longturn09
   速度: 593.75KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:49] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-longturn10
   速度: 593.75KB/s | 数据量: 0.6KB | 总耗时: 0.01s
[2025-09-25 09:12:49] ✅ 测速成功: http://breezy-audrie-zspace-7524863c.koyeb.app/vipsir?token=leifeng&id=litv-longturn13
   速度: 593.75KB/s | 数据量: 0.6KB | 总耗时: 0.02s
[2025-09-25 09:12:49] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv014
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:49] ✅ 测速成功: http://xtvantsc.xyz/litv_ts.php?id=4gtv-4gtv101
   速度: 583.01KB/s | 数据量: 0.6KB | 总耗时: 0.33s
[2025-09-25 09:12:50] ✅ 测速成功: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=litv-longturn19&sd=1080&proxy=false
   速度: 2396.48KB/s | 数据量: 2.4KB | 总耗时: 1.18s
[2025-09-25 09:12:50] ✅ 测速成功: https://live.iill.top/douyu/288016
   速度: 6582.03KB/s | 数据量: 6.6KB | 总耗时: 0.31s
[2025-09-25 09:12:50] ✅ 测速成功: https://live.iill.top/douyu/100
   速度: 6573.24KB/s | 数据量: 6.6KB | 总耗时: 0.26s
[2025-09-25 09:12:50] ✅ 测速成功: https://live.iill.top/douyu/1863767
   速度: 6584.96KB/s | 数据量: 6.6KB | 总耗时: 0.21s
[2025-09-25 09:12:50] ✅ 测速成功: https://live.iill.top/bilibili/55
   速度: 6579.10KB/s | 数据量: 6.6KB | 总耗时: 0.07s
[2025-09-25 09:12:50] ✅ 测速成功: https://live.iill.top/bilibili/6
   速度: 6576.17KB/s | 数据量: 6.6KB | 总耗时: 0.35s
[2025-09-25 09:12:50] ✅ 测速成功: https://live.iill.top/douyu/522423
   速度: 6603.52KB/s | 数据量: 6.6KB | 总耗时: 0.09s
[2025-09-25 09:12:50] ✅ 测速成功: https://live.iill.top/douyu/9715241
   速度: 6584.96KB/s | 数据量: 6.6KB | 总耗时: 0.09s
[2025-09-25 09:12:50] ✅ 测速成功: https://live.iill.top/douyu/999
   速度: 6573.24KB/s | 数据量: 6.6KB | 总耗时: 0.11s
[2025-09-25 09:12:50] ✅ 测速成功: https://live.iill.top/douyu/5388537
   速度: 6626.95KB/s | 数据量: 6.6KB | 总耗时: 0.09s
[2025-09-25 09:12:50] ✅ 测速成功: https://live.iill.top/douyu/3811559
   速度: 6584.96KB/s | 数据量: 6.6KB | 总耗时: 0.07s
[2025-09-25 09:12:50] ✅ 测速成功: https://live.iill.top/douyu/3226194
   速度: 1307.55KB/s | 数据量: 6.6KB | 总耗时: 0.08s
[2025-09-25 09:12:50] ✅ 测速成功: https://live.iill.top/douyu/7722576
   速度: 6564.45KB/s | 数据量: 6.6KB | 总耗时: 0.08s
[2025-09-25 09:12:50] ✅ 测速成功: https://live.iill.top/douyu/6672862
   速度: 6606.45KB/s | 数据量: 6.6KB | 总耗时: 0.08s
[2025-09-25 09:12:50] ✅ 测速成功: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=litv-longturn21&sd=1080&proxy=false
   速度: 2403.32KB/s | 数据量: 2.4KB | 总耗时: 4.53s
[2025-09-25 09:12:50] ✅ 测速成功: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=litv-longturn03&sd=1080&proxy=false
   速度: 2396.48KB/s | 数据量: 2.4KB | 总耗时: 4.38s
[2025-09-25 09:12:50] ❌ 测速失败: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=litv-longturn22&sd=1080&proxy=false
   错误: HTTPSConnectionPool(host='pxuchylhjchl.us-east-1.clawcloudrun.com', port=443): Read timed out. (read timeout=3.05) | 域名: pxuchylhjchl.us-east-1.clawcloudrun.com
[2025-09-25 09:12:51] ✅ 测速成功: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=litv-longturn20&sd=1080&proxy=false
   速度: 2396.48KB/s | 数据量: 2.4KB | 总耗时: 4.17s
[2025-09-25 09:12:51] ❌ 测速失败: https://pxuchylhjchl.us-east-1.clawcloudrun.com/index.m3u8?pid=4gtv-4gtv076&sd=1080&proxy=false
   错误: HTTPSConnectionPool(host='pxuchylhjchl.us-east-1.clawcloudrun.com', port=443): Read timed out. (read timeout=3.05) | 域名: pxuchylhjchl.us-east-1.clawcloudrun.com
[2025-09-25 09:12:52] ✅ 测速成功: http://liveflash.sxrtv.com/live/sxwshd.m3u8?sub_m3u8=true&edge_slice=true
   速度: 0.00KB/s | 数据量: 0.0KB | 总耗时: 2.13s
